apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
  labels:
    name: sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
  namespace: sonarr
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/sonarr/config
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
  namespace: sonarr
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/jellyfin/media/tv-shows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 250Mi
  volumeName: sonarr-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-downloads-pvc
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv-pvc
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
  volumeName: sonarr-tv-pv