apiVersion: v1
kind: Namespace
metadata:
  name: dashboard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-database
  namespace: dashboard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 250Mi
# Note: Secret must be created manually for security
# See README.md for instructions
