apiVersion: v1
kind: Namespace
metadata:
  name: jackett
  labels:
    name: jackett
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-config-pv
  namespace: jackett
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/jackett/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-pvc
  namespace: jackett
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
  volumeName: jackett-config-pv