apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: jackett
  labels:
    app: jackett
spec:
  type: LoadBalancer
  ports:
  - port: 9117
    targetPort: 9117
    protocol: TCP
    name: http
  selector:
    app: jackett
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-nodeport
  namespace: jackett
  labels:
    app: jackett
spec:
  type: NodePort
  ports:
  - port: 9117
    targetPort: 9117
    nodePort: 30117
    protocol: TCP
    name: http
  selector:
    app: jackett