apiVersion: v1
kind: Namespace
metadata:
  name: radarr
  labels:
    name: radarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  namespace: radarr
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/radarr/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
  namespace: radarr
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/sonarr/downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies-pv
  namespace: radarr
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/jellyfin/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
  volumeName: radarr-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Gi
  volumeName: radarr-downloads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies-pvc
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 2Ti
  volumeName: radarr-movies-pv