apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  type: LoadBalancer
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
    name: http
  selector:
    app: radarr
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-nodeport
  namespace: radarr
  labels:
    app: radarr
spec:
  type: NodePort
  ports:
  - port: 7878
    targetPort: 7878
    nodePort: 30878
    protocol: TCP
    name: http
  selector:
    app: radarr