---
apiVersion: v1
kind: Namespace
metadata:
  name: email
  labels:
    app.kubernetes.io/name: imap-server
    app.kubernetes.io/part-of: email-infrastructure
---
# Storage for mail data (Maildir format)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-data-pvc
  namespace: email
  labels:
    app.kubernetes.io/name: imap-server
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
---
# Note: Additional secrets like imap-credentials, dovecot-users, dovecot-ssl,
# aws-credentials, and tailscale secrets must be created manually for security
