---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
  labels:
    name: immich
---
# PersistentVolume for ML models on node05 NVMe
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-models-pv
  labels:
    app: immich-ml
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme-node05
  hostPath:
    path: /opt/immich/ml-models
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node05
---
# PVC for ML models on node05 NVMe
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-models-pvc
  namespace: immich
  labels:
    app: immich-ml
    component: ml-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-nvme-node05
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: immich-ml
---
# PVC for photo/video library storage (NFS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    app: immich
    component: library
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
---
# PVC for upload temporary storage (NFS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads-pvc
  namespace: immich
  labels:
    app: immich
    component: uploads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
---
# PVC for thumbnail storage (NFS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thumbs-pvc
  namespace: immich
  labels:
    app: immich
    component: thumbs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
---
# PVC for backup storage (NFS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-backups-pvc
  namespace: immich
  labels:
    app: immich
    component: backups
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Gi
