apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app: prowlarr
spec:
  type: NodePort
  ports:
    - port: 9696
      targetPort: 9696
      protocol: TCP
      name: http
      nodePort: 30996
  selector:
    app: prowlarr