apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-scripts
  namespace: transmission
data:
  move-by-label.sh: |
    #!/bin/sh
    # move-by-label.sh
    # Transmission post-download script to move finished downloads based on label (category)

    # Environment variables provided by Transmission:
    # $TR_TORRENT_NAME - Name of the torrent
    # $TR_TORRENT_DIR  - Directory where the torrent was downloaded
    # $TR_TORRENT_LABEL - Label (category) assigned to the torrent

    TORRENT_LABEL="$TR_TORRENT_LABEL"
    TORRENT_PATH="$TR_TORRENT_DIR/$TR_TORRENT_NAME"

    # Set your target directories (must match your PVC mounts in the container)
    SONARR_DIR="/downloads-sonarr"
    RADARR_DIR="/downloads-radarr"

    log() {
      echo "$(date '+%Y-%m-%d %H:%M:%S') [move-by-label] $1"
    }

    if [ -z "$TORRENT_LABEL" ]; then
      log "No label set for torrent '$TR_TORRENT_NAME'. Skipping move."
      exit 0
    fi

    case "$TORRENT_LABEL" in
      sonarr)
        log "Moving '$TORRENT_PATH' to $SONARR_DIR"
        mv "$TORRENT_PATH" "$SONARR_DIR/"
        ;;
      radarr)
        log "Moving '$TORRENT_PATH' to $RADARR_DIR"
        mv "$TORRENT_PATH" "$RADARR_DIR/"
        ;;
      *)
        log "Unknown label '$TORRENT_LABEL' for torrent '$TR_TORRENT_NAME'. Skipping move."
        ;;
    esac

    exit 0
