apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: pi-cluster
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2000"
    prometheus.io/path: "/metrics"
    prometheus.io/interval: "30s"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
  selector:
    app: cloudflared
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared-pdb
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: availability
    app.kubernetes.io/part-of: pi-cluster
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cloudflared
