apiVersion: v1
kind: Namespace
metadata:
  name: qbittorrent
  labels:
    name: qbittorrent
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
  namespace: qbittorrent
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/qbittorrent/config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
  namespace: qbittorrent
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/sonarr/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
  volumeName: qbittorrent-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Gi
  volumeName: qbittorrent-downloads-pv