apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: webui
  - port: 6881
    targetPort: 6881
    protocol: TCP
    name: torrent-tcp
  - port: 6881
    targetPort: 6881
    protocol: UDP
    name: torrent-udp
  selector:
    app: qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-nodeport
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: webui
  selector:
    app: qbittorrent