---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: dns
  labels:
    app: pihole
    component: dns-service
spec:
  type: LoadBalancer
  selector:
    app: pihole
    component: dns-server
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 31021
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 31021
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: dns
  labels:
    app: pihole
    component: web-service
spec:
  type: NodePort
  selector:
    app: pihole
    component: dns-server
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31080
  externalTrafficPolicy: Cluster
