apiVersion: v1
kind: Service
metadata:
  name: protonvpn
  namespace: vpn
  labels:
    app: protonvpn
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: control
  selector:
    app: protonvpn
---
apiVersion: v1
kind: Service
metadata:
  name: protonvpn-nodeport
  namespace: vpn
  labels:
    app: protonvpn
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30090
    protocol: TCP
    name: control
  selector:
    app: protonvpn