apiVersion: v1
kind: Namespace
metadata:
  name: jellyseerr
  labels:
    name: jellyseerr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/jellyseerr/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
  namespace: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 250Mi
  volumeName: jellyseerr-config-pv
