apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jellyseerr
  labels:
    app: jellyseerr
spec:
  type: NodePort
  ports:
    - port: 5055
      targetPort: 5055
      protocol: TCP
      name: http
      nodePort: 30055
  selector:
    app: jellyseerr
