apiVersion: v1
kind: Namespace
metadata:
  name: downloads
  labels:
    name: downloads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-downloads-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/shared/downloads
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-downloads-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
  volumeName: shared-downloads-pv