apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-pod
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: worker
  containers:
  - name: test-nfs-pod
    image: arm64v8/busybox:latest
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-nfs-claim
