# StorageClass for local NVMe storage on node05 (shared across applications)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nvme-node05
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-downloads-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/shared/downloads
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-downloads-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
