apiVersion: v1
kind: Namespace
metadata:
  name: homer
  labels:
    name: homer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-config-pv
  namespace: homer
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.88.163
    path: /mnt/storage/homer/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config-pvc
  namespace: homer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
  volumeName: homer-config-pv