apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: homer
        image: b4bz/homer:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: homer-config
          mountPath: /www/assets
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: homer-config
        persistentVolumeClaim:
          claimName: homer-config-pvc
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      tolerations:
      - key: "arm"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"