apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: homer
  labels:
    app: homer
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30800
  selector:
    app: homer
