---
title: "PiCluster Dashboard"
subtitle: "Kubernetes Media Server"
icon: "fas fa-home"

header: true
footer: '<p>Built with <span class="has-text-danger">❤️</span> on Raspberry Pi</p>'

theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"

services:
  - name: "Media Services"
    icon: "fas fa-play"
    items:
      - name: "Jellyfin"
        icon: "fas fa-film"
        subtitle: "Media streaming server"
        tag: "media"
        url: "http://192.168.88.162:8096"
        target: "_blank"

      - name: "Sonarr"
        icon: "fas fa-tv"
        subtitle: "TV show automation"
        tag: "automation"
        url: "http://192.168.88.162:8989"
        target: "_blank"

      - name: "Radarr"
        icon: "fas fa-video"
        subtitle: "Movie automation"
        tag: "automation"
        url: "http://192.168.88.162:7878"
        target: "_blank"

  - name: "Download & Indexing"
    icon: "fas fa-download"
    items:
      - name: "Transmission"
        icon: "fas fa-magnet"
        subtitle: "BitTorrent client with VPN"
        tag: "download"
        url: "http://192.168.88.162:9091"
        target: "_blank"

      - name: "Prowlarr"
        icon: "fas fa-search"
        subtitle: "Indexer manager"
        tag: "indexer"
        url: "http://192.168.88.162:30996"
        target: "_blank"

  - name: "Cluster Management"
    icon: "fas fa-cogs"
    items:
      - name: "Kubernetes Dashboard"
        icon: "fas fa-cubes"
        subtitle: "Cluster overview"
        tag: "admin"
        url: "https://192.168.88.162:30000"
        target: "_blank"

      - name: ArgoCD
        icon: " fas fa-code-branch"
        subtitle: GitOps for Kubernetes
        tag: "admin"
        url: http://192.168.88.162:30080
        target: "_blank"

      - name: "Grafana"
        icon: "fas fa-chart-line"
        subtitle: "Monitoring dashboards"
        tag: "monitoring"
        url: "http://192.168.88.162:30300"
        target: "_blank"

      - name: "Prometheus"
        icon: "fas fa-database"
        subtitle: "Metrics collection"
        tag: "monitoring"
        url: "http://192.168.88.162:30900"
        target: "_blank"
