---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  labels:
    app: homer
spec:
  project: default
  source:
    repoURL: https://github.com/t-p/PiCluster # Replace with your actual GitHub repository URL
    targetRevision: main
    path: apps/homer
  destination:
    server: https://kubernetes.default.svc
    namespace: homer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Homer dashboard"
    - name: "Documentation"
      value: "https://github.com/bastienwirtz/homer"
