---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  labels:
    app: jellyfin
spec:
  project: default
  source:
    repoURL: https://github.com/t-p/PiCluster
    targetRevision: main
    path: apps/jellyfin
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Jellyfin media server deployment for PiCluster"
    - name: "Documentation"
      value: "https://jellyfin.org/docs/"
