---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/t-p/PiCluster
    targetRevision: main
    path: apps/monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Prometheus + Grafana Kubernetes monitoring stack"
    - name: "Documentation"
      value: "https://github.com/prometheus-operator/kube-prometheus"
