---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  labels:
    app: prowlarr
spec:
  project: default
  source:
    repoURL: https://github.com/t-p/PiCluster
    targetRevision: main
    path: apps/prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: prowlarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Prowlarr indexer manager"
    - name: "Documentation"
      value: "https://github.com/Prowlarr/Prowlarr"
