---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  labels:
    app: radarr
spec:
  project: default
  source:
    repoURL: https://github.com/t-p/PiCluster
    targetRevision: main
    path: apps/radarr
  destination:
    server: https://kubernetes.default.svc
    namespace: downloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Radarr movie management server"
    - name: "Documentation"
      value: "https://wiki.servarr.com/radarr"
