---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-storage
  namespace: argocd
  labels:
    app: shared-storage
spec:
  project: default
  source:
    repoURL: https://github.com/t-p/PiCluster
    targetRevision: main
    path: apps/shared-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: downloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Manages shared NFS storage (shared-downloads-pvc) for all media apps"
    - name: "Documentation"
      value: "https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner"
